services:
  ubuntu-docker:
    build:
      context: .
      args:
        SSH_USER: ${SSH_USER}
        SSH_PASSWORD: ${SSH_PASSWORD}
    container_name: ubuntu-docker
    ports:
      - "2222:22"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 2g
    cpus: 1.0
    tty: true
    stdin_open: true
